title: Patrick's Tech Blog
description: Tech Blog Rambling of things I've figured out and want to remember

url: http://PLaroche.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

# navigation:
#  - title: Patrick Tech Blog
#    url: /index.html
 
social:
   github: plaroche
   twitter: plaroche
   email: patrick.laroche@smartsti.com

google_analytics: ""
